# The upstream server to proxy requests to
upstream: https://api.example.com

# The registered name of your company. From https://developers.eclypses.com
licenseCompany: Example, LLC.

# The license key for your company. From https://developers.eclypses.com
licenseKey: 0000000000000000

# A secret key used to sign cookies. 32+ character string is recommended.
cookieSecret: abcdefghijklmnopqrstuvwxyz0123456789

# The websites that are allowed to talk to this relay server
corsOrigins:
  - https://www.example.com
  - https://dashboard.example.com
  - http://localhost:3000

# An access token required to generate an MTE Usage report
# via this path: /api/mte-report/:accessToken
reportAccessToken: 55555555555555555555
# [OPTIONAL] Listen on this port. Must match EXPOSE port in Dockerfile.
# port: 8080

# [OPTIONAL] Pass-through routes, with no MTE Encryption
# passThroughRoutes:
#   - /api/example/1
#   - /api/example/2

# [OPTIONAL] A custom name for your cookie. A non-human-readable string is recommended.
# cookieName: abcdefgxyz

# [OPTIONAL] Define allowed CORS methods. Below values match default values.
# corsMethods:
#   - GET
#   - POST
#   - PUT
#   - DELETE

# [OPTIONAL] If provided, the proxy server to connect to a Redis database.
# redisConnectionString: redis://redis.example.com:6379
